version: '3.8'

services:
  web:
    image: draakbzh/docker-test:latest
    ports:
      - "3001:3001"
    environment:
      MYSQL_ROOT_PASSWORD: rootdraak
      MYSQL_DATABASE: draakdb
      MYSQL_USER: draak
      MYSQL_PASSWORD: draakpassword
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdraak
      MYSQL_DATABASE: draakdb
      MYSQL_USER: draak 
      MYSQL_PASSWORD: draakpassword 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
